Fail if more scenarios fail
ScottLogic/openapi-forge pull request #106
Opened 2022-10-19 14:12 UTC by jhowlett-scottlogic

PR for issue: https://github.com/ScottLogic/openapi-forge/issues/87

- Save test results from workflow as a .json file.
- Add step that retrieves test results .json file from most recent push to master. 
- Add step which runs a .js script that for each language compares the two files.
- Fails if languages exist in both json files and:
    - more tests in new run: newFailedTotal - oldFailedTotal > numberOfAddedTests
    - less tests in new run:  newFailedTotal - oldFailedTotal > 0
    - This allows for tests to be added and not cause the testing to fail.
- Fix bug that would result in a non-zero exit code when tests pass

Please excuse the obscene number of commits and degeneration of commit messages. To develop I had to create a commit to trigger the workflow to run.

This will set up the generator state webpage nicely https://github.com/ScottLogic/openapi-forge/issues/69 as all that will be needed is a new workflow that updates the webpage .md file with the new tests results from the json.

2022-10-19 19:41 UTC, ColinEberhardt requested changes
a few minor comments, but otherwise looks really good.

2022-10-19 19:41 UTC, ColinEberhardt commented
> Please excuse the obscene number of commits and degeneration of commit messages. To develop I had to create a commit to trigger the workflow to run.

No worries - a squash will fix that 👍

2022-10-20 07:49 UTC, jhowlett-scottlogic commented on src/index.js
> +    "-r, --reportResults",
Ahh yes that is in the forge command too

2022-10-20 08:15 UTC, ColinEberhardt commented on src/index.js
> +  .option(
Could this be changed to ...

~~~
.option(
    "-o, --outputFile <file>",
    "Writes the testing results to a JSON file",
    "test-results.json"
  )
~~~

2022-10-20 09:47 UTC, jhowlett-scottlogic commented on src/index.js
> +  .option(
I have made a slight tweak to the implementation of this requested change. The reason is that this proposed solution would result in a file always being generated. With my version only when the argument `-o` is given does it write an output. If no path is given it uses the default (test-results.json) and if given it uses the given path.

2022-10-20 11:00 UTC, ColinEberhardt approved these changes

2022-10-20 12:33 UTC, merged