feat: group by tag
ScottLogic/openapi-forge pull request #123
Opened 2022-11-08 16:58 UTC by jhowlett-scottlogic

PR for issue: https://github.com/ScottLogic/openapi-forge/issues/18

Separate paths by first tag in 'tags' array

2022-11-08 17:00 UTC, jhowlett-scottlogic commented
Testing will probably fail as it requires the new generators

2022-11-08 17:41 UTC, ColinEberhardt requested changes
This looks like a really good start, thanks @jhowlett-scottlogic 

I do think the test scenarios need a little more work. They should be as. close to a 'plain English' description of the desired functionality as possible. Ideally you should write them ahead of implementation (so that the implementation doesn't influence the specification!)

Your 'no op' test cases all look good, and it is great to see you are testing all the various cases where tags are not used.

For tagged APIs, I'd expect the test cases to more explicitly validate that an API file named 'users' is generated, and that this file contains specific methods.

For inspiration, take a look at this test scenario - you can add additional when statements, or then statements to invoke multiple methods, or navigate around the API.

2022-11-08 17:47 UTC, ColinEberhardt commented on src/generate.js
> +          schema._tags.forEach((tag) => {
this block of code has a few repeated concepts - the `template(schema)` is applied twice, as is writing the output files.

Would it be possible to refactor, so that there is just a single place where the template is executed and the output file written?

Perhaps it would be easier if you always had an array of tags? i.e. for the case where you have no tags, perhaps just have an empty tag? This would remove some of the need for branching.

2022-11-09 09:30 UTC, jhowlett-scottlogic commented
Regarding your comment about testing presence of some API files and not others. The current implementation of the testing only allows for 1 API file and so this was the best i could do without a major rewrite of the testing set up.

See in C# - tests/FeaturesTests/TestHelper.cs:66 where only one API type is set
See in ts - features/support/api.ts:29 where only one API is set

I can change this to handle an array of API files so the can all be checked. I didn't think this would be best because for 99% of cases there will only be one as only one or a select few endpoints will be tested so an array of APIs would be an unnecessary complication.

I am currently looking into resetting the API mid scenario to a different tag so that it can test different API files in the same scenario.

2022-11-09 15:46 UTC, jhowlett-scottlogic commented on src/generate.js
> +          schema._tags.forEach((tag) => {
I have refactored as much as possible so that it uses two method calls and in that method the templating and formatting is completed.

The reason for the different behaviour is that the API files are generated in a loop using the tag array and the other files are not looped and so not in a for-loop.

The array cannot be altered to set it to [""] when not an API file because the tag array is generated during the schema transformation phase.

2022-11-10 15:17 UTC, ColinEberhardt approved these changes
thanks for the updates - looks good to me 👍

2022-11-10 16:58 UTC, merged