Generator options
ScottLogic/openapi-forge pull request #154
Opened 2023-01-26 18:27 UTC by ms14981

I'm not convinced by the file structure, so let me know if you have a more sensible idea!

2023-01-26 18:28 UTC, ms14981 commented on src/commands/forgeCommand.js
> +        generatorResolver.cleanup();
I moved this cleanup because it was happening before we'd finished with the  files

2023-01-27 10:35 UTC, gkocak-scottlogic approved these changes
👍

2023-01-27 13:22 UTC, ColinEberhardt requested changes
A couple of minor comments.

I'm quite happy with the proposed folder structure

2023-01-27 13:22 UTC, ColinEberhardt commented on src/generatorOptions/index.js
> +      log.standard(await generatorOptions(generator));
I don't think the use of `log.standard` makes sense here. Currently the logging module allows us to configure the verbosity of the forge command. In this instance, I can't see a reason to hide the generator options output, also this command doesn't support setting the verbosity either.

On that note, perhaps the log module lives in the `src/forge` folder?

2023-01-27 13:22 UTC, ColinEberhardt commented on src/forge/index.js
> +        // set the additional options as environment variables
Thinking how these options might be used ...

Adding them as environment variables makes them accessible to helpers, which is how they're used in the [JavaScript generator](https://github.com/ScottLogic/openapi-forge-javascript/blob/main/helpers/import.js#L2). However, I can think of other instances where you might want to access them from the handlebars template.

I think it is worth adding them to the schema object, in the same way that 'standard' options are added:

https://github.com/ScottLogic/openapi-forge/blob/master/src/generate.js#L212

2023-01-31 10:27 UTC, ms14981 commented on src/forge/index.js
> +        // set the additional options as environment variables
It is already added. When running
```
./src/index.js forge https://petstore3.swagger.io/api/v3/openapi.json https://github.com/ScottLogic/openapi-forge-javascript.git -o js -l verbose --generator.moduleFormat "esmodule"
```
schema._options becomes

```
{
  "exclude": "",
  "output": "js",
  "logLevel": "verbose",
  "generator.moduleFormat": "esmodule"
}
```
Is this what you meant, or did you mean something different?

2023-01-31 11:52 UTC, ms14981 commented on src/generatorOptions/index.js
> +      log.standard(await generatorOptions(generator));
Changed the log line. Moved the log file to `src/common/`

2023-02-01 10:13 UTC, ColinEberhardt commented on src/forge/index.js
> +        // set the additional options as environment variables
Oh, perfect, that does the trick :-)

2023-02-01 10:14 UTC, merged