Test all language generators in one command
ScottLogic/openapi-forge pull request #58
Opened 2022-09-07 08:45 UTC by jhowlett-scottlogic

Using openapi-forge test-generators you can test all language generators and then have a table of results presented. 

This command searches for a local language generators or uses the version hosted on GitHub.

2022-09-07 09:13 UTC, jhowlett-scottlogic commented
This approach uses a search and replace in some files (2 for TypeScript & 1 for CSharp) that refererences openapi-forge in the node_modules folder.  Instead these file paths are repalced to the local version of the generator and then reverted back. 

An alternative approach would be to have a separate configuration file in each language generator that would house these file paths (and another other variable data) and then the language generators will have a different configuration file when using the new test-generators  command compared to using the testing that is in each of the language generators.

A small refactoring to help prevent this testing from breaking if the file path lines change causing the regex patterns to start failing. 

Let me know what you think and i can bring this change in.

2022-09-08 08:42 UTC, ColinEberhardt requested changes
functionally works very well, but could do with a bit more refactoring.

2022-09-08 08:42 UTC, ColinEberhardt commented on README.md
> +% openapi-forge help test-generators
Adding as a new command for the CLI is a great idea 👍

2022-09-08 08:42 UTC, ColinEberhardt commented on README.md
> +  -c, --csharp <csharpPath>          Sets the location of the CSharp generator. Default is a directory called 'openapi-forge-csharp' in the same location as
_aside_ should the forge have hard-coded references to the generators?

2022-09-08 08:42 UTC, ColinEberhardt commented on src/generate.js
> +    if (schema?.components?.schemas) {
much cleaner

2022-09-08 08:42 UTC, ColinEberhardt commented on src/testGenerators.js
> +    let temporaryFolder;
having lots of mutable variables is a bit of a 'code smell'!

2022-09-08 08:42 UTC, ColinEberhardt commented on src/testGenerators.js
> +    if(typescript) {
From a 30,000 foot view I can see that code of a similar shape is duplicated later in this function. It is also quite long, and as more language generators are added will need refactoring. A sign that it is worth investing some more time in re-structuring.

2022-09-08 08:42 UTC, ColinEberhardt commented on src/testGenerators.js
> +            if (!fs.existsSync(generatorPath)) {
idea 💡 - this resolution process is something that is used twice in this function, but also, the generator itself has to perform this resolution. Could this be abstracted into a 'resolver', you give it a generator reference, it takes care of going away and finding it.

2022-09-08 08:42 UTC, ColinEberhardt commented on src/testGenerators.js
> +            log.verbose("Replacing path to .feature files");
I'm really not sure why we need to change file paths? this feels quite fragile.

2022-09-08 08:42 UTC, ColinEberhardt commented on src/testGenerators.js
> +            let result = stdout[stdoutLength-2].match(/^(\d+)m(\d+)\.\d+s/);
regex is a super powerful tool, but hard to maintain. Please make sure that you add a brief comment that explains the regex.

2022-09-08 08:42 UTC, ColinEberhardt commented on src/testGenerators.js
> +            if(result) {
It looks like this code is parsing the TypeScript / cuccumber output in order to locate the test results. All looks good, but perhaps refactor this into a seperate file? `TestResultsParser` perhaps?

2022-09-08 08:42 UTC, ColinEberhardt commented on src/testGenerators.js
> +                if(!temporaryFolder) {
See comment about generator resolving - could that also have responsibility for maintaining paths?

2022-09-08 08:42 UTC, ColinEberhardt commented on src/testGenerators.js
> +            if (temporaryFolder) {
clean-up could also be a job for the resolver?

2022-09-14 15:19 UTC, jhowlett-scottlogic commented on src/testGenerators.js
> +    let temporaryFolder;
increased immutability

2022-09-14 15:20 UTC, jhowlett-scottlogic commented on src/testGenerators.js
> +    if(typescript) {
I have extracted duplicated logic to separate functions, generatorResolver.js or testResultParser.js

2022-09-14 15:21 UTC, jhowlett-scottlogic commented on src/testGenerators.js
> +            log.verbose("Replacing path to .feature files");
Now uses cl arguments to configure the generators

2022-09-14 15:23 UTC, jhowlett-scottlogic commented on src/testGenerators.js
> +            let result = stdout[stdoutLength-2].match(/^(\d+)m(\d+)\.\d+s/);
I have added a small commnet above Regex uses to help explain them

2022-09-14 15:23 UTC, jhowlett-scottlogic commented on src/testGenerators.js
> +            if(result) {
done

2022-09-14 15:24 UTC, jhowlett-scottlogic commented on src/testGenerators.js
> +                if(!temporaryFolder) {
generatorResolver.js handles getting and disposing of generators

2022-09-14 15:24 UTC, jhowlett-scottlogic commented on src/testGenerators.js
> +            if (!fs.existsSync(generatorPath)) {
done

2022-09-14 15:50 UTC, jhowlett-scottlogic commented
Changes since previous review:

- Handle new cl arguments in generator's `npm test`
- Extract parsing test results to testResultParser.js
- Extract generator download ans cleanup to generatorResolver.js
- Extract repeated logic in testGenerators()
- House shellOptions in log.js for one unified shellOptions

2022-09-15 07:52 UTC, ColinEberhardt approved these changes

2022-09-15 07:52 UTC, merged