Fix prettier errors
ScottLogic/openapi-forge pull request #66
Opened 2022-09-26 14:13 UTC by jhowlett-scottlogic

2022-09-26 15:43 UTC, ColinEberhardt requested changes
one very minor request.

2022-09-26 15:43 UTC, ColinEberhardt commented on src/log.js
> +  verbose("");
can you eslint ignore this section so that the original formatting can be retained?

2022-09-27 14:02 UTC, ColinEberhardt commented
> yes i missed that, i have added it now

thanks @jhowlett-scottlogic - feel free to merge when you've resolved conflicts

2022-09-28 08:03 UTC, jhowlett-scottlogic commented
@ColinEberhardt this needs re-reviewing before it can be merged as you have requested changes

2022-09-29 13:44 UTC, ColinEberhardt approved these changes

2022-09-29 14:20 UTC, merged