Include API metadata in output
ScottLogic/openapi-forge pull request #81
Opened 2022-09-29 12:44 UTC by osouthwell-scottlogic

Adds two new helpers and removes new lines in info description. 
This is needed to add the metadata to the output
#16

2022-09-29 13:37 UTC, ColinEberhardt requested changes
A few comments ...

2022-09-29 13:37 UTC, ColinEberhardt commented on src/generate.js
> +    schema.info.description = JSON.stringify(schema.info.description);
A couple of minor points ...

 1. Transformation of the schema should be handled in the `transformers.js` logic
 2. Rather than mutate the schema, I'd prefer to add new properties. In other words, keep `description` intact, and add `_description`
 3. Not really sure what the JSON stringify / parse is for?

2022-10-03 14:49 UTC, ColinEberhardt requested changes

2022-10-03 14:49 UTC, ColinEberhardt commented on src/transformers.js
> +   schema._info.description = schema.info.description.replace(/(?:\r|\n)/g, " ");
Unless I’m mistaken, this will still mutate ‘into.description’ - the line above just creates a new reference to the same object.

JS spread operator should fix this … 

‘schema._info = { …schema.info, description: /** your code here **/ }’

2022-10-03 14:57 UTC, osouthwell-scottlogic commented on src/transformers.js
> +   schema._info.description = schema.info.description.replace(/(?:\r|\n)/g, " ");
You're right, I hadn't commit the change. I like using the spread operator to keep it tidy

2022-10-03 15:42 UTC, ColinEberhardt approved these changes
👍👍👍

2022-10-12 14:25 UTC, jhowlett-scottlogic approved these changes
LGTM

2022-10-12 14:26 UTC, merged